export const WINDOWS = [
  {
    id: 'info',
    title: 'Info',
    icon: 'assets/icons/wordpad.png',
    width: 420,
    height: 360,
    src: 'pages/info/index.html',
  },
  {
    id: 'terminal',
    title: 'Terminal',
    icon: 'assets/icons/terminal.png',
    width: 600,
    height: 400,
    src: 'pages/terminal/index.html',
  },
  {
    id: 'resume',
    title: 'Resume',
    icon: 'assets/icons/ie.png',
    shortcut: true,
    width: 800,
    height: 520,
    src: 'pages/resume/index.html',
  },
  {
    id: 'projects',
    title: 'Projects',
    icon: 'assets/icons/folder.png',
    width: 560,
    height: 420,
    src: 'pages/projects/index.html',
  },
  {
    id: 'games',
    title: 'Games',
    icon: 'assets/icons/games.png',
    width: 560,
    height: 420,
    src: 'pages/games/index.html',
  },
  {
    id: 'music',
    title: 'Music',
    icon: 'assets/icons/mediaplayer.png',
    width: 560,
    height: 420,
    src: 'pages/music/index.html',
  },
];
